chore(deps): update dependency eslint to v8.57.0 (#274)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [eslint](https://eslint.org)
([source](https://togithub.com/eslint/eslint)) | [`8.55.0` ->
`8.57.0`](https://renovatebot.com/diffs/npm/eslint/8.55.0/8.57.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint/8.57.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint/8.57.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint/8.55.0/8.57.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint/8.55.0/8.57.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>eslint/eslint (eslint)</summary>

### [`v8.57.0`](https://togithub.com/eslint/eslint/releases/tag/v8.57.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.56.0...v8.57.0)

#### Features

-
[`1120b9b`](https://togithub.com/eslint/eslint/commit/1120b9b7b97f10f059d8b7ede19de2572f892366)
feat: Add loadESLint() API method for v8
([#&#8203;18098](https://togithub.com/eslint/eslint/issues/18098))
(Nicholas C. Zakas)
-
[`dca7d0f`](https://togithub.com/eslint/eslint/commit/dca7d0f1c262bc72310147bcefe1d04ecf60acbc)
feat: Enable `eslint.config.mjs` and `eslint.config.cjs`
([#&#8203;18066](https://togithub.com/eslint/eslint/issues/18066))
(Nitin Kumar)

#### Bug Fixes

-
[`2196d97`](https://togithub.com/eslint/eslint/commit/2196d97094ba94d6d750828879a29538d1600de5)
fix: handle absolute file paths in `FlatRuleTester`
([#&#8203;18064](https://togithub.com/eslint/eslint/issues/18064))
(Nitin Kumar)
-
[`69dd1d1`](https://togithub.com/eslint/eslint/commit/69dd1d1387b7b53617548d1f9f2c149f179e6e17)
fix: Ensure config keys are printed for config errors
([#&#8203;18067](https://togithub.com/eslint/eslint/issues/18067))
(Nitin Kumar)
-
[`9852a31`](https://togithub.com/eslint/eslint/commit/9852a31edcf054bd5d15753ef18e2ad3216b1b71)
fix: deep merge behavior in flat config
([#&#8203;18065](https://togithub.com/eslint/eslint/issues/18065))
(Nitin Kumar)
-
[`4c7e9b0`](https://togithub.com/eslint/eslint/commit/4c7e9b0b539ba879ac1799e81f3b6add2eed4b2f)
fix: allow circular references in config
([#&#8203;18056](https://togithub.com/eslint/eslint/issues/18056))
(Milos Djermanovic)

#### Documentation

-
[`84922d0`](https://togithub.com/eslint/eslint/commit/84922d0bfa10689a34a447ab8e55975ff1c1c708)
docs: Show prerelease version in dropdown
([#&#8203;18139](https://togithub.com/eslint/eslint/issues/18139))
(Nicholas C. Zakas)
-
[`5b8c363`](https://togithub.com/eslint/eslint/commit/5b8c3636a3d7536535a6878eca0e5b773e4829d4)
docs: Switch to Ethical Ads
([#&#8203;18117](https://togithub.com/eslint/eslint/issues/18117))
(Milos Djermanovic)
-
[`77dbfd9`](https://togithub.com/eslint/eslint/commit/77dbfd9887b201a46fc68631cbde50c08e1a8dbf)
docs: show NEXT in version selectors
([#&#8203;18052](https://togithub.com/eslint/eslint/issues/18052))
(Milos Djermanovic)

#### Chores

-
[`1813aec`](https://togithub.com/eslint/eslint/commit/1813aecc4660582b0678cf32ba466eb9674266c4)
chore: upgrade
[@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).57.0
([#&#8203;18143](https://togithub.com/eslint/eslint/issues/18143))
(Milos Djermanovic)
-
[`5c356bb`](https://togithub.com/eslint/eslint/commit/5c356bb0c6f53c570224f8e9f02c4baca8fc6d2f)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (Jenkins)
-
[`f4a1fe2`](https://togithub.com/eslint/eslint/commit/f4a1fe2e45aa1089fe775290bf530de82f34bf16)
test: add more tests for ignoring files and directories
([#&#8203;18068](https://togithub.com/eslint/eslint/issues/18068))
(Nitin Kumar)
-
[`42c0aef`](https://togithub.com/eslint/eslint/commit/42c0aefaf6ea8b998b1c6db61906a79c046d301a)
ci: Enable CI for `v8.x` branch
([#&#8203;18047](https://togithub.com/eslint/eslint/issues/18047))
(Milos Djermanovic)

### [`v8.56.0`](https://togithub.com/eslint/eslint/releases/tag/v8.56.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.55.0...v8.56.0)

##### Features

-
[`0dd9704`](https://togithub.com/eslint/eslint/commit/0dd9704c4751e1cd02039f7d6485fee09bbccbf6)
feat: Support custom severity when reporting unused disable directives
([#&#8203;17212](https://togithub.com/eslint/eslint/issues/17212))
(Bryan Mishkin)
-
[`31a7e3f`](https://togithub.com/eslint/eslint/commit/31a7e3fde491e36496b54e8905c766b31162d776)
feat: fix no-restricted-properties false negatives with unknown objects
([#&#8203;17818](https://togithub.com/eslint/eslint/issues/17818)) (Arka
Pratim Chaudhuri)

##### Bug Fixes

-
[`7d5e5f6`](https://togithub.com/eslint/eslint/commit/7d5e5f68849ae80caec0fc96ecceebccd348deec)
fix: `TypeError: fs.exists is not a function` on read-only file system
([#&#8203;17846](https://togithub.com/eslint/eslint/issues/17846))
(Francesco Trotta)
-
[`74739c8`](https://togithub.com/eslint/eslint/commit/74739c849bbb6547b0e555ed8bb2ba1cbe0fdce4)
fix: suggestion with invalid syntax in no-promise-executor-return rule
([#&#8203;17812](https://togithub.com/eslint/eslint/issues/17812))
(Bryan Mishkin)

##### Documentation

-
[`9007719`](https://togithub.com/eslint/eslint/commit/90077199fe519953f9af8664bf947db4e4958514)
docs: update link in ways-to-extend.md
([#&#8203;17839](https://togithub.com/eslint/eslint/issues/17839)) (Amel
SELMANE)
-
[`3a22236`](https://togithub.com/eslint/eslint/commit/3a22236f8d10af8a5bcafe56092651d3d681c99d)
docs: Update README (GitHub Actions Bot)
-
[`54c3ca6`](https://togithub.com/eslint/eslint/commit/54c3ca6f2dcd2a7afd53f42fc32055a25587259e)
docs: fix migration-guide example
([#&#8203;17829](https://togithub.com/eslint/eslint/issues/17829))
(Tanuj Kanti)
-
[`4391b71`](https://togithub.com/eslint/eslint/commit/4391b71e62b15e54b0493f0dce1ea053ebbc0689)
docs: check config comments in rule examples
([#&#8203;17815](https://togithub.com/eslint/eslint/issues/17815))
(Francesco Trotta)
-
[`fd28363`](https://togithub.com/eslint/eslint/commit/fd2836342c2be4751b05fe0ba7cece17d1edecc8)
docs: remove mention about ESLint stylistic rules in readme
([#&#8203;17810](https://togithub.com/eslint/eslint/issues/17810))
(Zwyx)
-
[`48ed5a6`](https://togithub.com/eslint/eslint/commit/48ed5a6dad478a14d3e823f137455c523f373e0b)
docs: Update README (GitHub Actions Bot)

##### Chores

-
[`ba6af85`](https://togithub.com/eslint/eslint/commit/ba6af85c7d8ba55d37f8663aee949d148e441c1a)
chore: upgrade
[@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).56.0
([#&#8203;17864](https://togithub.com/eslint/eslint/issues/17864))
(Milos Djermanovic)
-
[`60a531a`](https://togithub.com/eslint/eslint/commit/60a531a9c0811ddf718e26b9136e133f580b6c36)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (Jenkins)
-
[`ba87a06`](https://togithub.com/eslint/eslint/commit/ba87a0651a65b52c3ac442b512dd9f4c2b4c5f57)
chore: update dependency markdownlint to ^0.32.0
([#&#8203;17783](https://togithub.com/eslint/eslint/issues/17783))
(renovate\[bot])
-
[`9271d10`](https://togithub.com/eslint/eslint/commit/9271d10d9eabeafb0129a090f29191bfd14273c0)
chore: add GitHub issue template for docs issues
([#&#8203;17845](https://togithub.com/eslint/eslint/issues/17845)) (Josh
Goldberg ✨)
-
[`70a686b`](https://togithub.com/eslint/eslint/commit/70a686b3c1feac5eca98bbff9bd67175f550d5db)
chore: Convert rule tests to FlatRuleTester
([#&#8203;17819](https://togithub.com/eslint/eslint/issues/17819))
(Nicholas C. Zakas)
-
[`f3a599d`](https://togithub.com/eslint/eslint/commit/f3a599d34c7080fc0b2c9a60b5e54dc98c22867c)
chore: upgrade eslint-plugin-unicorn to v49.0.0
([#&#8203;17837](https://togithub.com/eslint/eslint/issues/17837)) (唯然)
-
[`905d4b7`](https://togithub.com/eslint/eslint/commit/905d4b75ab2df42aba30622cee0f66b511397e2c)
chore: upgrade eslint-plugin-eslint-plugin v5.2.1
([#&#8203;17838](https://togithub.com/eslint/eslint/issues/17838)) (唯然)
-
[`4d7c3ce`](https://togithub.com/eslint/eslint/commit/4d7c3ce246e6b499f472342ef59496a47cc033d6)
chore: update eslint-plugin-n v16.4.0
([#&#8203;17836](https://togithub.com/eslint/eslint/issues/17836)) (唯然)
-
[`fd0c60c`](https://togithub.com/eslint/eslint/commit/fd0c60c3be1f213e5a6d69d8a3248e963619e155)
ci: unpin Node.js 21.2.0
([#&#8203;17821](https://togithub.com/eslint/eslint/issues/17821))
(Francesco Trotta)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/danvk/literate-ts).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4yNjkuMiIsInVwZGF0ZWRJblZlciI6IjM3LjI2OS4yIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>